import { MOCK_IDS } from '@/lib/mock-ids';
import { songSchema } from '@/schemas/song.schema';

import z from 'zod';

export type Song = z.infer<typeof songSchema>;

export const mockSongs: Song[] = [
  {
    id: MOCK_IDS.SONGS.TENGO_MUCHO_RUIDO,
    title: 'tengo mucho ruido.',
    album: 'TODOS LOS DÍAS TODO EL DÍA',
    artist: 'Latin Mafia',
    artistId: MOCK_IDS.ARTISTS.LATIN_MAFIA,
    duration: 202,
    image: '/images/albums/todos-los-dias-todo-el-dia.webp',
    url: '/audio/tengo-mucho-ruido.opus',
  },
  {
    id: MOCK_IDS.SONGS.YO_SIEMPRE_CONTESTO,
    title: 'Yo siempre contesto.',
    album: 'TODOS LOS DÍAS TODO EL DÍA',
    artist: 'Latin Mafia',
    artistId: MOCK_IDS.ARTISTS.LATIN_MAFIA,
    duration: 200,
    image: '/images/albums/todos-los-dias-todo-el-dia.webp',
    url: '/audio/yo-siempre-contesto.opus',
  },
  {
    id: MOCK_IDS.SONGS.LOVE_NEVER_FELT_SO_GOOD,
    title: 'Love Never Felt So Good',
    album: 'Xscape',
    artist: 'Michael Jackson',
    artistId: MOCK_IDS.ARTISTS.MICHAEL_JACKSON,
    duration: 247,
    image: '/images/albums/xscape.webp',
    url: '/audio/love-never-felt-so-good.opus',
  },
  {
    id: MOCK_IDS.SONGS.BILLIE_JEAN,
    title: 'Billie Jean',
    album: 'Thriller',
    artist: 'Michael Jackson',
    artistId: MOCK_IDS.ARTISTS.MICHAEL_JACKSON,
    duration: 295,
    image: '/images/albums/thriller.webp',
    url: '/audio/billie-jean.opus',
  },
  {
    id: MOCK_IDS.SONGS.THE_GREAT_GIG_IN_THE_SKY,
    title: 'The Great Gig in the Sky',
    album: 'The Dark Side of the Moon',
    artist: 'Pink Floyd',
    artistId: MOCK_IDS.ARTISTS.PINK_FLOYD,
    duration: 284,
    image: '/images/albums/the-dark-side-of-the-moon.webp',
    url: '/audio/the-great-gig-in-the-sky.opus',
  },
  {
    id: MOCK_IDS.SONGS.WISH_YOU_WERE_HERE,
    title: 'Wish You Were Here',
    album: 'Wish You Were Here',
    artist: 'Pink Floyd',
    artistId: MOCK_IDS.ARTISTS.PINK_FLOYD,
    duration: 293,
    image: '/images/albums/wish-you-were-here.webp',
    url: '/audio/wish-you-were-here.opus',
  },
  {
    id: MOCK_IDS.SONGS.TRATAME_SUAVEMENTE,
    title: 'Trátame Suavemente',
    album: 'Soda Stereo',
    artist: 'Soda Stereo',
    artistId: MOCK_IDS.ARTISTS.SODA_STEREO,
    duration: 202,
    image: '/images/albums/soda-stereo.webp',
    url: '/audio/tratame-suavemente.opus',
  },
  {
    id: MOCK_IDS.SONGS.PERSIANA_AMERICANA,
    title: 'Persiana Americana',
    album: 'Signos',
    artist: 'Soda Stereo',
    artistId: MOCK_IDS.ARTISTS.SODA_STEREO,
    duration: 293,
    image: '/images/albums/signos.webp',
    url: '/audio/persiana-americana.opus',
  },
  {
    id: MOCK_IDS.SONGS.LUTHER_WITH_SZA,
    title: 'luther (with sza)',
    album: 'GNX',
    artist: 'Kendrick Lamar',
    artistId: MOCK_IDS.ARTISTS.KENDRICK_LAMAR,
    duration: 177,
    image: '/images/albums/gnx.webp',
    url: '/audio/luther-with-sza.opus',
  },
  {
    id: MOCK_IDS.SONGS.PRIDE,
    title: 'PRIDE.',
    album: 'DAMN.',
    artist: 'Kendrick Lamar',
    artistId: MOCK_IDS.ARTISTS.KENDRICK_LAMAR,
    duration: 275,
    image: '/images/albums/damn.webp',
    url: '/audio/pride.opus',
  },
  {
    id: MOCK_IDS.SONGS.SI_NUNCA_VA_A_AMANECER,
    title: 'Si Nunca Va a Amanecer',
    album: 'Smile',
    artist: 'Charles Ans',
    artistId: MOCK_IDS.ARTISTS.CHARLES_ANS,
    duration: 215,
    image: '/images/albums/smile.webp',
    url: '/audio/si-nunca-va-a-amanecer.opus',
  },
  {
    id: MOCK_IDS.SONGS.AQUI_TODO_ESTA_BIEN,
    title: 'Aquí Todo Esta Bien',
    album: 'Smile',
    artist: 'Charles Ans',
    artistId: MOCK_IDS.ARTISTS.CHARLES_ANS,
    duration: 242,
    image: '/images/albums/smile.webp',
    url: '/audio/aqui-todo-esta-bien.opus',
  },
  {
    id: MOCK_IDS.SONGS.ONE_MINUTE_MORE,
    title: 'One Minute More',
    album: 'In a Tidal Wave of Mystery',
    artist: 'Capital Cities',
    artistId: MOCK_IDS.ARTISTS.CAPITAL_CITIES,
    duration: 202,
    image: '/images/albums/in-a-tidal-wave-of-mystery.webp',
    url: '/audio/one-minute-more.opus',
  },
  {
    id: MOCK_IDS.SONGS.KANGAROO_COURT,
    title: 'Kangaroo Court',
    album: 'In a Tidal Wave of Mystery',
    artist: 'Capital Cities',
    artistId: MOCK_IDS.ARTISTS.CAPITAL_CITIES,
    duration: 223,
    image: '/images/albums/in-a-tidal-wave-of-mystery.webp',
    url: '/audio/kangaroo-court.opus',
  },
  {
    id: MOCK_IDS.SONGS.UNICOS,
    title: 'Únicos',
    album: 'Únicos',
    artist: 'Siddhartha',
    artistId: MOCK_IDS.ARTISTS.SIDDHARTHA,
    duration: 252,
    image: '/images/albums/unicos.webp',
    url: '/audio/unicos.opus',
  },
  {
    id: MOCK_IDS.SONGS.TARDE,
    title: 'Tarde',
    album: 'Únicos',
    artist: 'Siddhartha',
    artistId: MOCK_IDS.ARTISTS.SIDDHARTHA,
    duration: 259,
    image: '/images/albums/unicos.webp',
    url: '/audio/tarde.opus',
  },
  {
    id: MOCK_IDS.SONGS.WHAT_YOU_WONT_DO_FOR_LOVE,
    title: "What You Won't Do for Love",
    album: "What You Won't Do for Love",
    artist: 'Bobby Caldwell',
    artistId: MOCK_IDS.ARTISTS.BOBBY_CALDWELL,
    duration: 286,
    image: '/images/albums/what-you-wont-do-for-love.webp',
    url: '/audio/what-you-wont-do-for-love.opus',
  },
  {
    id: MOCK_IDS.SONGS.MY_FLAME,
    title: 'My Flame',
    album: "What You Won't Do for Love",
    artist: 'Bobby Caldwell',
    artistId: MOCK_IDS.ARTISTS.BOBBY_CALDWELL,
    duration: 252,
    image: '/images/albums/what-you-wont-do-for-love.webp',
    url: '/audio/my-flame.opus',
  },
  {
    id: MOCK_IDS.SONGS.ISNT_SHE_LOVELY,
    title: "Isn't She Lovely",
    album: 'The Definitive Collection',
    artist: 'Stevie Wonder',
    artistId: MOCK_IDS.ARTISTS.STEVIE_WONDER,
    duration: 200,
    image: '/images/albums/the-definitive-collection.webp',
    url: '/audio/isnt-she-lovely.opus',
  },
  {
    id: MOCK_IDS.SONGS.PARTE_TIME_LOVER,
    title: 'Part Time Lover',
    album: 'The Definitive Collection',
    artist: 'Stevie Wonder',
    artistId: MOCK_IDS.ARTISTS.STEVIE_WONDER,
    duration: 254,
    image: '/images/albums/the-definitive-collection.webp',
    url: '/audio/part-time-lover.opus',
  },
];
