import { songSchema } from '@/schemas/song.schema';

import z from 'zod';

export type Song = z.infer<typeof songSchema>;

export const mockSongs: Song[] = [
  {
    id: '1',
    title: 'tengo mucho ruido.',
    album: 'TODOS LOS DÍAS TODO EL DÍA',
    artist: 'Latin Mafia',
    artistId: '1',
    duration: 202,
    image: '/images/albums/todos-los-dias-todo-el-dia.webp',
    url: '/audio/tengo-mucho-ruido.opus',
  },
  {
    id: '2',
    title: 'Yo siempre contesto.',
    album: 'TODOS LOS DÍAS TODO EL DÍA',
    artist: 'Latin Mafia',
    artistId: '1',
    duration: 200,
    image: '/images/albums/todos-los-dias-todo-el-dia.webp',
    url: '/audio/yo-siempre-contesto.opus',
  },
  {
    id: '3',
    title: 'Love Never Felt So Good',
    album: 'Xscape',
    artist: 'Michael Jackson',
    artistId: '2',
    duration: 247,
    image: '/images/albums/xscape.webp',
    url: '/audio/love-never-felt-so-good.opus',
  },
  {
    id: '4',
    title: 'Billie Jean',
    album: 'Thriller',
    artist: 'Michael Jackson',
    artistId: '2',
    duration: 295,
    image: '/images/albums/thriller.webp',
    url: '/audio/billie-jean.opus',
  },
  {
    id: '5',
    title: 'The Great Gig in the Sky',
    album: 'The Dark Side of the Moon',
    artist: 'Pink Floyd',
    artistId: '3',
    duration: 284,
    image: '/images/albums/the-dark-side-of-the-moon.webp',
    url: '/audio/the-great-gig-in-the-sky.opus',
  },
  {
    id: '6',
    title: 'Wish You Were Here',
    album: 'Wish You Were Here',
    artist: 'Pink Floyd',
    artistId: '3',
    duration: 293,
    image: '/images/albums/wish-you-were-here.webp',
    url: '/audio/wish-you-were-here.opus',
  },
  {
    id: '7',
    title: 'Trátame Suavemente',
    album: 'Soda Stereo',
    artist: 'Soda Stereo',
    artistId: '4',
    duration: 202,
    image: '/images/albums/soda-stereo.webp',
    url: '/audio/tratame-suavemente.opus',
  },
  {
    id: '8',
    title: 'Persiana Americana',
    album: 'Signos',
    artist: 'Soda Stereo',
    artistId: '4',
    duration: 293,
    image: '/images/albums/signos.webp',
    url: '/audio/persiana-americana.opus',
  },
  {
    id: '9',
    title: 'luther (with sza)',
    album: 'GNX',
    artist: 'Kendrick Lamar',
    artistId: '5',
    duration: 177,
    image: '/images/albums/gnx.webp',
    url: '/audio/luther-with-sza.opus',
  },
  {
    id: '10',
    title: 'PRIDE.',
    album: 'DAMN.',
    artist: 'Kendrick Lamar',
    artistId: '5',
    duration: 275,
    image: '/images/albums/damn.webp',
    url: '/audio/pride.opus',
  },
  {
    id: '11',
    title: 'Si Nunca Va a Amanecer',
    album: 'Smile',
    artist: 'Charles Ans',
    artistId: '6',
    duration: 215,
    image: '/images/albums/smile.webp',
    url: '/audio/si-nunca-va-a-amanecer.opus',
  },
  {
    id: '12',
    title: 'Aquí Todo Esta Bien',
    album: 'Smile',
    artist: 'Charles Ans',
    artistId: '6',
    duration: 242,
    image: '/images/albums/smile.webp',
    url: '/audio/aqui-todo-esta-bien.opus',
  },
  {
    id: '13',
    title: 'One Minute More',
    album: 'In a Tidal Wave of Mystery',
    artist: 'Capital Cities',
    artistId: '7',
    duration: 202,
    image: '/images/albums/in-a-tidal-wave-of-mystery.webp',
    url: '/audio/one-minute-more.opus',
  },
  {
    id: '14',
    title: 'Kangaroo Court',
    album: 'In a Tidal Wave of Mystery',
    artist: 'Capital Cities',
    artistId: '7',
    duration: 223,
    image: '/images/albums/in-a-tidal-wave-of-mystery.webp',
    url: '/audio/kangaroo-court.opus',
  },
  {
    id: '15',
    title: 'Únicos',
    album: 'Únicos',
    artist: 'Siddhartha',
    artistId: '8',
    duration: 252,
    image: '/images/albums/unicos.webp',
    url: '/audio/unicos.opus',
  },
  {
    id: '16',
    title: 'Tarde',
    album: 'Únicos',
    artist: 'Siddhartha',
    artistId: '8',
    duration: 259,
    image: '/images/albums/unicos.webp',
    url: '/audio/tarde.opus',
  },
  {
    id: '17',
    title: "What You Won't Do for Love",
    album: "What You Won't Do for Love",
    artist: 'Bobby Caldwell',
    artistId: '9',
    duration: 286,
    image: '/images/albums/what-you-wont-do-for-love.webp',
    url: '/audio/what-you-wont-do-for-love.opus',
  },
  {
    id: '18',
    title: 'My Flame',
    album: "What You Won't Do for Love",
    artist: 'Bobby Caldwell',
    artistId: '9',
    duration: 252,
    image: '/images/albums/what-you-wont-do-for-love.webp',
    url: '/audio/my-flame.opus',
  },
  {
    id: '19',
    title: "Isn't She Lovely",
    album: 'The Definitive Collection',
    artist: 'Stevie Wonder',
    artistId: '10',
    duration: 200,
    image: '/images/albums/the-definitive-collection.webp',
    url: '/audio/isnt-she-lovely.opus',
  },
  {
    id: '20',
    title: 'Part Time Lover',
    album: 'The Definitive Collection',
    artist: 'Stevie Wonder',
    artistId: '10',
    duration: 254,
    image: '/images/albums/the-definitive-collection.webp',
    url: '/audio/part-time-lover.opus',
  },
];
